"""Engine-independent game inspection contracts."""

from .models import (
    ArchiveEntryInspection,
    ArchiveInspection,
    GameInspectionReport,
    QlieEntryProbeReport,
    QlieScriptExportItem,
    QlieScriptExportPlan,
    QlieScriptExportResult,
    QlieScriptSurveyFile,
    QlieScriptSurveyReport,
    QlieScriptSyntaxShape,
    QlieTocInspectionReport,
)
from .segments import (
    SEGMENT_SCHEMA_VERSION,
    SegmentContractError,
    SegmentInlineToken,
    SegmentSource,
    TextSegment,
    build_text_segment,
    link_segment_sequence,
    normalize_segment_text,
    segments_from_jsonl,
    segments_to_jsonl,
)

__all__ = [
    "ArchiveEntryInspection",
    "ArchiveInspection",
    "GameInspectionReport",
    "QlieEntryProbeReport",
    "QlieScriptExportItem",
    "QlieScriptExportPlan",
    "QlieScriptExportResult",
    "QlieScriptSurveyFile",
    "QlieScriptSurveyReport",
    "QlieScriptSyntaxShape",
    "QlieTocInspectionReport",
    "SEGMENT_SCHEMA_VERSION",
    "SegmentContractError",
    "SegmentInlineToken",
    "SegmentSource",
    "TextSegment",
    "build_text_segment",
    "link_segment_sequence",
    "normalize_segment_text",
    "segments_from_jsonl",
    "segments_to_jsonl",
]
